// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8SS58UTqYlrQPttt0W9YL_r228jC3lQ8',
    appId: '1:931423454032:web:0cac6f40bff113c2fae255',
    messagingSenderId: '931423454032',
    projectId: 'crewapplicationprogram',
    authDomain: 'crewapplicationprogram.firebaseapp.com',
    storageBucket: 'crewapplicationprogram.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoGnZlzBCdgbC-kFNrACIE2T3QOJsyVP8',
    appId: '1:931423454032:android:f3943f7d43ae6676fae255',
    messagingSenderId: '931423454032',
    projectId: 'crewapplicationprogram',
    storageBucket: 'crewapplicationprogram.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyMIFT32P8ujjVwdUT_R34BJG0xQQylws',
    appId: '1:931423454032:ios:ef2f5c67747cadb6fae255',
    messagingSenderId: '931423454032',
    projectId: 'crewapplicationprogram',
    storageBucket: 'crewapplicationprogram.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyMIFT32P8ujjVwdUT_R34BJG0xQQylws',
    appId: '1:931423454032:ios:ef2f5c67747cadb6fae255',
    messagingSenderId: '931423454032',
    projectId: 'crewapplicationprogram',
    storageBucket: 'crewapplicationprogram.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8SS58UTqYlrQPttt0W9YL_r228jC3lQ8',
    appId: '1:931423454032:web:e07b3b3680f251a9fae255',
    messagingSenderId: '931423454032',
    projectId: 'crewapplicationprogram',
    authDomain: 'crewapplicationprogram.firebaseapp.com',
    storageBucket: 'crewapplicationprogram.firebasestorage.app',
  );
}
